pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- script: docker build -t pgarneau/notification-service . # include other options to meet your needs
- script: |
    docker login -u pgarneau -p devildanger1984
    docker push pgarneau/notification-service