jobs:
- job: Build
  steps:
  - script: docker build -t notificus/notification-service .
    condition: always()
  - script: docker login -u notificus -p c2Mwk-Mc && docker push notificus/notification-service
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
